services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserverapi
    ports:
      - "1433:1433"
    env_file:
      - .env.defaults
      - .env
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

  webapi:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: DockerAPI
      env_file:
        - .env.defaults
        - .env
      depends_on:
        - sqlserver
      ports:
        - "8080:8080"
      volumes:
      - .:/app

volumes:
  sqlserver_data: